#In this yaml file we are defining the path of  project stages like dataingestion,basemodel...so on
artifact_root_dir: artifacts

#stage 1:-Dataingestion stage
Dataingestion:
  ingestion_root_dir_path: artifacts/Dataingestion
  zip_dir_path: artifacts/Dataingestion/
  unzip_dir_path: artifacts/Dataingestion/


#stage2:- we are using baseModel vgg16 and using trainable parameter(weights and bias)
#to create sequential class of tensorflow

prepare_base_model:
  root_dirpath: artifacts/base_model
  base_model_path: artifacts/base_model/basemodel.h5
  updated_base_model_path: artifacts/base_model/updated_model.h5


