#In this yaml file we are defining the path of  project stages like dataingestion,basemodel...so on
artifact_root_dir: artifacts

#stage 1:-Dataingestion stage
Dataingestion:
  ingestion_root_dir_path: artifacts/Dataingestion
  zip_dir_path: artifacts/Dataingestion/
  unzip_dir_path: artifacts/Dataingestion/


#stage2:- we are using baseModel vgg16 and using trainable parameter(weights and bias)
#to create sequential class of tensorflow

prepare_base_model:
  root_dirpath: artifacts/base_model
  base_model_path: artifacts/base_model/basemodel.h5
  updated_base_model_path: artifacts/base_model/updated_model.h5


#stage3:-in this stage we create checkpoint directory(to get best model) or tensorboar directory to log the error in it
prepare_callbacks:
  root_dirpath: artifacts/callbacks
  tensorboard_log_dirpath: artifacts/callbacks/tensorboard_log_dir #this directory we save our logs files init
  model_checkpoint_path: artifacts/callbacks/model_checkpoint/model.h5 #in this path after training done save the best model file in name of model.h5


